export const section = ["Baby & Toddler Toys",
  "Baby Lotion",
  "Baby Massage Oil",
  "Baby Powder",
  "Baby Shampoos",
  "Baby Soaps",
  "Diapers",
  "Briefs & Trunks",
  "Socks & Handkerchiefs",
  "Vests",
  "Leggings & Chudidar",
  "Pyjama Sets",
  "Socks & Handkerchiefs",
  "Coffee",
  "Concentrates",
  "Energy Drinks",
  "Green Tea",
  "Soda & Water",
  "Soft Drinks",
  "Squash & Syrups",
  "Tea Bags",
  "Tea",
  "Butter",
  "Cheese",
  "Curd",
  "Yogurt",
  "Blended Oil",
  "Groundnut Oil",
  "Mustard Oil",
  "Olive Oil",
  "Other Oils",
  "Rice Bran Oil",
  "Sunflower Oil",
  "Chana Dal",
  "Daliya",
  "Masoor Dal",
  "Mix Dal",
  "Moong Dal",
  "Urad Dal",
  "Almonds",
  "Anjeer",
  "Apricot",
  "Cashews",
  "Dates",
  "Makhana",
  "Mixed Dryfruits",
  "Pista",
  "Raisins",
  "Walnuts",
  "Atta",
  "Grains",
  "Other Flours",
  "Ghee",
  "Vanaspati",
  "Chilli Powder",
  "Cooking Pastes",
  "Coriander Powder",
  "Food Essence",
  "Herbs & Seasonings",
  "Powdered Spices",
  "Turmeric Powder",
  "Whole Spices",
  "Chana",
  "Chowli",
  "Groundnut",
  "Masoor",
  "Moong",
  "Rajma",
  "Soya Products",
  "Urad",
  "Basmati Rice",
  "Brown Rice",
  "Kolam Rice",
  "Kurmura",
  "Other Rice",
  "Poha",
  "Jaggery",
  "Salt",
  "Sugar",
  "Floor Cleaners",
  "Other Cleaners",
  "Toilet Cleaners",
  "Detergent Bar",
  "Detergent Powder",
  "Liquid Detergent",
  "Disinfectant Liquid & Spray",
  "Air Fresheners",
  "Mosquito Bat",
  "Repellents",
  "Cabinets",
  "Chair Covers",
  "Table Runner",
  "Wall Clocks",
  "Agarbatti & Dhoop",
  "Camphor & Kapur",
  "Decorative Accessories",
  "Festive Candles",
  "Pooja Items",
  "Bottles",
  "Flasks",
  "Lunch Box",
  "Aluminium Foils",
  "Tissue Paper & Napkins",
  "Toilet Paper",
  "Brooms & Dust Pans",
  "Gloves",
  "Hardware",
  "Kitchen Aprons",
  "Mops & Refills",
  "Cat Food",
  "Bread & Buns",
  "Cakes",
  "Cookies",
  "Digestive Biscuits",
  "Glucose Biscuits",
  "Khari & Toasts",
  "Flakes",
  "Muesli",
  "Chocolates",
  "Dark Chocolates",
  "Gums / Mints / Candies",
  "Parathas & Rotis",
  "Snacks",
  "Veggies",
  "Beverages",
  "Biscuits & Chocolates",
  "Dark Chocolates",
  "Ketchup & Sauces",
  "Noodles & Pasta",
  "Honey",
  "Jams",
  "Mayonnaise",
  "Spreads",
  "Chutney",
  "Ketchup",
  "Vinegar",
  "Hakka Noodles",
  "Pasta",
  "Vermicelli",
  "Chilli Pickles",
  "Chutney & Chutney Powder",
  "Mango Pickles",
  "Mixed Pickles",
  "Other Pickles",
  "Popcorn",
  "Soups",
  "Chips & Wafers",
  "Namkeens",
  "Other Snacks",
  "Bath Soaps & Bars",
  "Talcum Powders",
  "Hair Colour",
  "Hair Combs",
  "Hair Conditioners",
  "Hair Gels & Creams",
  "Hair Oils",
  "Hair Serums",
  "Hair Shampoos",
  "Antiseptics",
  "Chyawanprash",
  "Cold Relief",
  "Contraceptives",
  "Digestive Care",
  "Ear Care",
  "First Aid",
  "Other Healthy Alternatives",
  "Pain Relief",
  "Sugar Substitutes",
  "Vitamins & Supplements",
  "After Shave",
  "Face Wash",
  "Shaving Cream & Brushes",
  "Shaving Foam",
  "Shaving Razors",
  "Mouthwash",
  "Toothbrushes",
  "Toothpaste",
  "Adult Diapers",
  "Hand Wash & Sanitizers",
  "Intimate Wash",
  "Lip Balms",
  "Sunscreen",
  "Decoration",
  "Raincoat",
  "Umbrella",
  "Blankets",
  "Pillow Covers",
  "Pillows",
  "Gas Stoves",
  "Mixers",
  "Toasters & Induction Cooktops",
  "Curtains",
  "Glues / Tapes & More",
  "Files & Folders",
  "Notebooks"
];